#!/usr/bin/env bash
# One-time AWS bootstrap for Nova BBVA on App Runner (keep it simple).
#
# Prerequisites:
#   - AWS account + `aws configure` (IAM user with admin or PowerUser for first run)
#   - Docker installed locally (for first manual deploy) OR use GitHub Actions after this
#
# Usage:
#   export AWS_REGION=eu-west-1
#   export ANTHROPIC_API_KEY=sk-ant-...
#   ./scripts/aws/bootstrap.sh

set -euo pipefail

AWS_REGION="${AWS_REGION:-eu-west-1}"
SERVICE_NAME="${APP_RUNNER_SERVICE_NAME:-nova-bbva-aws}"
ECR_REPO="${ECR_REPO_NAME:-arc-one/nova-bbva-aws}"
SECRET_NAME="${ANTHROPIC_SECRET_NAME:-arc-one/nova-bbva-aws/anthropic-api-key}"

if ! command -v aws >/dev/null 2>&1; then
  echo "Install AWS CLI: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html" >&2
  exit 1
fi

ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
ECR_URI="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}"

echo "Account: ${ACCOUNT_ID} · Region: ${AWS_REGION}"
echo "ECR: ${ECR_URI}"
echo ""

# ECR repository
if ! aws ecr describe-repositories --repository-names "${ECR_REPO}" --region "${AWS_REGION}" >/dev/null 2>&1; then
  echo "→ Creating ECR repository ${ECR_REPO}..."
  aws ecr create-repository \
    --repository-name "${ECR_REPO}" \
    --image-scanning-configuration scanOnPush=true \
    --region "${AWS_REGION}" >/dev/null
else
  echo "→ ECR repository ${ECR_REPO} already exists"
fi

# Anthropic API key in Secrets Manager (optional — pass ANTHROPIC_API_KEY at deploy time instead)
SECRET_ARN=""
if ! aws secretsmanager describe-secret --secret-id "${SECRET_NAME}" --region "${AWS_REGION}" >/dev/null 2>&1; then
  if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
    echo "→ Creating secret ${SECRET_NAME}..."
    aws secretsmanager create-secret \
      --name "${SECRET_NAME}" \
      --secret-string "${ANTHROPIC_API_KEY}" \
      --region "${AWS_REGION}" >/dev/null
    SECRET_ARN="$(aws secretsmanager describe-secret --secret-id "${SECRET_NAME}" --region "${AWS_REGION}" --query ARN --output text)"
  else
    echo "→ Skipping Secrets Manager (pass ANTHROPIC_API_KEY at deploy time)"
  fi
else
  echo "→ Secret ${SECRET_NAME} already exists"
  if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
    echo "  Updating secret value..."
    aws secretsmanager put-secret-value \
      --secret-id "${SECRET_NAME}" \
      --secret-string "${ANTHROPIC_API_KEY}" \
      --region "${AWS_REGION}" >/dev/null
  fi
  SECRET_ARN="$(aws secretsmanager describe-secret --secret-id "${SECRET_NAME}" --region "${AWS_REGION}" --query ARN --output text)"
fi

# App Runner access role (pull from ECR)
ACCESS_ROLE_NAME="${APP_RUNNER_ACCESS_ROLE:-AppRunnerECRAccessRole-nova-bbva}"
if ! aws iam get-role --role-name "${ACCESS_ROLE_NAME}" >/dev/null 2>&1; then
  echo "→ Creating IAM role ${ACCESS_ROLE_NAME}..."
  aws iam create-role \
    --role-name "${ACCESS_ROLE_NAME}" \
    --assume-role-policy-document '{
      "Version": "2012-10-17",
      "Statement": [{
        "Effect": "Allow",
        "Principal": { "Service": "build.apprunner.amazonaws.com" },
        "Action": "sts:AssumeRole"
      }]
    }' >/dev/null
  aws iam attach-role-policy \
    --role-name "${ACCESS_ROLE_NAME}" \
    --policy-arn arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess
  echo "  Waiting for IAM propagation..."
  sleep 10
else
  echo "→ IAM role ${ACCESS_ROLE_NAME} already exists"
fi
ACCESS_ROLE_ARN="$(aws iam get-role --role-name "${ACCESS_ROLE_NAME}" --query Role.Arn --output text)"

# Instance role for Secrets Manager (runtime env)
INSTANCE_ROLE_NAME="${APP_RUNNER_INSTANCE_ROLE:-AppRunnerInstanceRole-nova-bbva}"
if ! aws iam get-role --role-name "${INSTANCE_ROLE_NAME}" >/dev/null 2>&1; then
  echo "→ Creating instance IAM role ${INSTANCE_ROLE_NAME}..."
  aws iam create-role \
    --role-name "${INSTANCE_ROLE_NAME}" \
    --assume-role-policy-document '{
      "Version": "2012-10-17",
      "Statement": [{
        "Effect": "Allow",
        "Principal": { "Service": "tasks.apprunner.amazonaws.com" },
        "Action": "sts:AssumeRole"
      }]
    }' >/dev/null
  POLICY_DOC="$(cat <<EOF
{
  "Version": "2012-10-17",
  "Statement": [{
    "Effect": "Allow",
    "Action": ["secretsmanager:GetSecretValue"],
    "Resource": "${SECRET_ARN:-*}"
  }]
}
EOF
)"
  aws iam put-role-policy \
    --role-name "${INSTANCE_ROLE_NAME}" \
    --policy-name NovaBbvaSecretsRead \
    --policy-document "${POLICY_DOC}"
  sleep 5
else
  echo "→ Instance IAM role ${INSTANCE_ROLE_NAME} already exists"
fi
INSTANCE_ROLE_ARN="$(aws iam get-role --role-name "${INSTANCE_ROLE_NAME}" --query Role.Arn --output text)"

mkdir -p "$(dirname "$0")/../../.aws-bootstrap"
cat > "$(dirname "$0")/../../.aws-bootstrap/env.sh" <<EOF
# Generated by scripts/aws/bootstrap.sh — source before deploy
export AWS_REGION=${AWS_REGION}
export AWS_ACCOUNT_ID=${ACCOUNT_ID}
export ECR_REPO_NAME=${ECR_REPO}
export ECR_URI=${ECR_URI}
export APP_RUNNER_SERVICE_NAME=${SERVICE_NAME}
export APP_RUNNER_ACCESS_ROLE_ARN=${ACCESS_ROLE_ARN}
export APP_RUNNER_INSTANCE_ROLE_ARN=${INSTANCE_ROLE_ARN}
export ANTHROPIC_SECRET_ARN=${SECRET_ARN}
export ANTHROPIC_SECRET_NAME=${SECRET_NAME}
EOF

echo ""
echo "✅ Bootstrap complete. Saved .aws-bootstrap/env.sh"
echo ""
echo "Next:"
echo "  1. source .aws-bootstrap/env.sh"
echo "  2. ./scripts/aws/deploy.sh"
echo "  3. Mint Arc One token as tecnico@bbva → GitHub secrets → register (see README)"
echo ""
echo "GitHub Actions vars (repository):"
echo "  AWS_REGION=${AWS_REGION}"
echo "  AWS_ACCOUNT_ID=${ACCOUNT_ID}"
echo "  ECR_REPO_NAME=${ECR_REPO}"
echo "  APP_RUNNER_SERVICE_NAME=${SERVICE_NAME}"
